### PR TITLE
add option to ignore the player's gamemode when pasting

### PR DESCRIPTION
**Pull request by Ethernalll**
Add the option to ignore the player's gamemode when attempting to paste a schematic

### CODE REVIEW

**Comment by maruohon** [comment]
This makes no sense to me. Why would anyone want to paste a schematic for free in anything other than creative mode?

In my opinion if you want "fast and automated schematic building in survival", then use either one of the printer extension mods, or Baritone to build the schematic.

**Comment by Ethernalll** [comment]
I don't see how it doesn't make sense, you have options to set what commands it uses or change how the command gets called, but then it's hardcoded to creative mode only.
If you're against it then that's that, I just thought it'd be a neat addition.

**Comment by maruohon** [comment]
Okay maybe if you have some custom command that actually uses the items... But even so that would then essentially be a printer in the mod itself, and personally I feel a printer is too cheaty for survival. That's why I also abandoned the idea of even including a printer in the mod itself although initially I said it would have one at some point. I'm just leaving it for extension mods.

But personally I just think that anything that is based on commands does not fit in survival, and I don't want to take the mod into a "more cheaty" direction. On the contrary I have been thinking about even removing the Easy Place mode from the base mod and moving it to an extension mod. And in that line of thinking I think this would also better fit in an extension mod.

Maybe I need to make some additional changes to make it easier to make such an extension mod without having to resort to using Mixins. During the on-going rewrites I'm trying to make the mods easier to extend and create extension mods for, without having to use Mixins to modify the base mod.

**Comment by Ethernalll** [comment]
> Okay maybe if you have some custom command that actually uses the items.

yep, that's what I have, and I spent the last few days making it before finally testing it in survival, which lead me to make this PR. but I understand your concern, maybe I'll just fiddle with making some kind of extension mod.

Thank you for your time.

**Pull request closed without merging**
