### PR TITLE
Add hello plugin message

### PR DESCRIPTION
**Pull request by ghost**
Allows better compatibility server-side.

### CODE REVIEW

**Comment by Onako2** [comment]
Wouldn't this allow the server to kick players that use the mod? I often play on Minecraft servers with strong anti-cheats and they kick the player once a packet is sent/recieved that is not a usual one. That would make compatibility even worse!

**Comment by ghost** [comment]
> Wouldn't this allow the server to kick players that use the mod? I often play on Minecraft servers with strong anti-cheats and they kick the player once a packet is sent/recieved that is not a usual one. That would make compatibility even worse!

The compatibility comes from the fact the server server knows we are using litematica, without this, using easyplace would cause you to be banned since it flags numerous anti-cheat checks.

**Comment by Onako2** [comment]
There is another issue that cheat clients will begin to say that they are litematica even if litematica isn't installed

**Comment by sakura-ryoko** [comment]
I do not see this as being a wise idea, especially in snapshot / 1.20.5+ versions of Minecraft, all packets need to get registered so this code would in fact potentially cause Minecraft to crash with an unknown / unregisterred payload.

Perhaps don't use Easy Place (Such as for mid-air blocks) so you don't get banned?

**Comment by ghost** [comment]
> There is another issue that cheat clients will begin to say that they are litematica even if litematica isn't installed

It is up to the server to handle what checks should be enabled/disabled if litematica is used.

**Comment by ghost** [comment]
> I do not see this as being a wise idea, especially in snapshot / 1.20.5+ versions of Minecraft, all packets need to get registered so this code would in fact potentially cause Minecraft to crash with an unknown / unregisterred payload.
> 
> Perhaps don't use Easy Place (Such as for mid-air blocks) so you don't get banned?

Unfortunately everybody uses easy place, which causes them to get false banned, and there is no way to determine if someone is using litematica or not, hence this PR.

**Comment by sakura-ryoko** [comment]
> Unfortunately everybody uses easy place, which causes them to get false banned, and there is no way to determine if someone is using litematica or not, hence this PR.

I would recommend making a forked version for your server for the interm unless Masa decides to do something with this.  For 1.20.5+ there may be other packet channels to watch, again, depending on what Masa decides to go with from my DEV code for networking.

But then again I still don't see this as a litematica issue in particular.

**Pull request closed without merging**
