### PR TITLE
Update to 1.20

### PR DESCRIPTION
**Pull request by y2k04**
I used [ekgame/malilib (pre-rewrite/fabric/1.20.x)](https://github.com/ekgame/malilib/tree/pre-rewrite/fabric/1.20.x) which works completely fine.

Bug that I caused: Material List block icons are empty.
image

I forgotten which class renders the icons in the material list, could someone please remind me?

### CODE REVIEW

**Comment by y2k04** [comment]
I forgotten which class renders the icons in the material list, could someone please remind me?

**Comment by vacla** [comment]
@y2k04 see: https://github.com/maruohon/malilib/pull/126#issuecomment-1586179815

**Comment by y2k04** [comment]
> @y2k04 see: [maruohon/malilib#126 (comment)](https://github.com/maruohon/malilib/pull/126#issuecomment-1586179815)

What forks?

**Comment by vacla** [comment]
Like https://github.com/kosmolot-mods/litematica that currently most ppl are using for 1.20

**Comment by y2k04** [comment]
Ohh thanks, but I will be keeping this pull request up.

**Comment by Fradid** [comment]
Why i cant compile kosmolot-mods/litematica? it says you dont have malilib-1.20-0.16.0.jar, but i do

**Comment by y2k04** [comment]
> Why i cant compile kosmolot-mods/litematica? it says you dont have malilib-1.20-0.16.0.jar, but i do

You have to add malilib-1.20-0.16.0.jar and malilib-1.20-0.16.0.pom to `%userprofile%\.gradle\fabric-loom\minecraftMaven\fi\dy\masa\malilib\malilib-fabric-1.20\0.16.0`. You will probably need to make the folders yourself.

I have attached malilib-1.20-0.16.0.pom but you will need to remove .txt from the end of it.

[malilib-fabric-1.20-0.16.0.pom.txt](https://github.com/maruohon/litematica/files/11777797/malilib-fabric-1.20-0.16.0.pom.txt)

**Comment by Fradid** [comment]
oh yeah, this is just what I needed, I couldn't find the file. ty so much!

**Comment by y2k04** [comment]
I have been testing out the unofficial version of Litematica by kosmolot and it has been a lot better and doesn't have the issue of the item icons in the material list not being drawn. If you go to the Modrinth page for it, download the .mrpack, open it in 7-Zip or something similar, go into the override folder and extract Litematica and MaliLib. It works fine.

**Comment by maruohon** [comment]
@y2k04 Are you saying the item rendering is broken in the official release for you? It seems to work in my test instance at least.

**Comment by y2k04** [comment]
> @y2k04 Are you saying the item rendering is broken in the official release for you? It seems to work in my test instance at least.

In my fork, the items in the material list don't render.

**Pull request closed without merging**
