### PR TITLE
Added translations into russian

### PR DESCRIPTION
**Pull request by Felix14-v2**
Almost a complete translation of the interface into Russian (excluding a couple of lines that I couldn't find in the GUI).

### CODE REVIEW

**Review by Felix14-v2 — COMMENTED** [review]
New strings from #423

**Comment by Felix14-v2** [comment]
It doesn't seem like anyone is interested in this...

**Comment by maruohon** [comment]
Looks like I missed this when I looked for any "relevant" PRs recently. I can locally merge this to the 1.18 branch (I'm not working on 1.17 anymore for the time being).

**Comment by Felix14-v2** [comment]
Then should I create another PR for 1.18?
I try to keep the translations up to date.
By the way, as far as I know, Litematica has versions for older Minecraft versions. For example, 1.12.2 is still very popular for players with weak computers playing on servers. If necessary, I can convert translations into their format as well.

**Comment by maruohon** [comment]
I already merged this PR to the 1.18 branch. I think there might be a few new and changed translations in that branch though... I'll push it tomorrow and you can then take a look if there are changes needed. I did also change and add some comments today for the paste and fill and delete related things.

As for 1.12.2, yes the 1.12.2 LiteLoader branch is still the main development version. It just hasn't had any work put into it for almost 2 years now due to me being busy with malilib rewrites and mod ports/updates on the later MC versions using the old code base. And also during the on-going rewrites of the mods in 1.12.2 pretty much all of the translations will get updated and cleaned up, so don't bother working on them for 1.12.2 just yet. Maybe I'll post a comment here if I remember once it's time to make/update the translations on 1.12.2. Those will then also replace all the 1.13+ versions once that rewrite code gets ported forward.

**Pull request closed without merging**
