### PR TITLE
Blocks below carpets get removed by "visible blocks only"

### LINKED ISSUE #772: Blocks get removed by the "visible blocks only"  when there is a carpet on top
In the pre-rewrite 1.20.x (and earlier) version there is the experimental feature to save "visible blocks only". Since the bottom side of carpets is a full solid square, blocks below carpets may be removed by this setting. But these blocks are necessary to place the carpet and should not be removed.

### PR DESCRIPTION
**Pull request by MichaelVolk**
fixes #772

### CODE REVIEW

**Comment by Crec0** [comment]
Blocks which require a supporting material should also be covered by this PR since they have similar limitation. Snow Layers, Repeaters, Comparators, Dust, etc.

**Comment by MichaelVolk** [comment]
That's true for snow layers, repeaters and comparators. Redstone dust is already covered since its bottom side is not a full square.
Sadly, I lack the programming experience for implementing repeaters, comparators and snow layers (are there more non full blocks needing a support block?).

**Comment by Crec0** [comment]
I am pretty sure there's a helper method somewhere which checks if the material requires supporting blocks in a particular direction. Maybe that can be used here.

**Comment by maruohon** [comment]
I didn't find any common/generic methods to indicate blocks that need support. So I just added an implementation with hard coded blocks. I also added a new option to the save menu to enable this "support blocks" behavior. It also adds a support block for gravity block columns that have some part of the column exposed.



The visible blocks implementation still has issues like where it would just leave out stuff like fully concealed redstone stuff like repeaters... But I don't know if it's worth it to worry about stuff like that (for now at least), I feel like this option would mostly be used for large scale aesthetic builds instead of redstone contraptions.

**Comment by MichaelVolk** [comment]
Thank you for implementing this!

**Pull request closed without merging**
