### PR TITLE
Adds interval configuration for halting easyPlace on inventory swap

### PR DESCRIPTION
**Pull request by mms0316**
- When on high ping, servers may misplace a block with what was in the hotbar before the swap happened
- Tested in an Airplane server

### CODE REVIEW

**Comment by mms0316** [comment]
Fixes #113

**Comment by mms0316** [comment]
Showcasing why this is important:
https://streamable.com/3bitpa

**Comment by maruohon** [comment]
I know this happens sometimes, but this proposed change is more of a band-aid for the underlying issue... of which I'm not entirely sure why it happens as I haven't properly looked into it yet.

But what should be happening, is that the slot click packets and the possible active hand slot change packet are sent first, before the item use packet. But sometimes the player still seems to end up placing the wrong block... On the client side the mod always checks what is in the players hand, so the item is correct on the client side at the time of doing the simulated item use. So what I suspect may be happening is that either the Paper based server hits the packet limit of like 4 packets per tick, and then it drops some of the slot click packets or the current slot change packet. But I think this sometimes also happens on other servers, so this may not be the reason, or at least the only reason. Another thing that might happen is that there is an inventory de-sync of some kind, maybe the server syncs older inventory state to the client and some of the later packets are yet to arrive and update the inventory state further, and the client uses the intermediary old/wrong items in some slot click actions, which would then result in the server disagreeing on the next inventory actions and re-syncing the entire inventory.

So I guess I might pull this fix for now, but I would also like to investigate what exactly happens with these wrongly placed blocks, ie. when and what inventory update packets the client receives interleaved how with the item use packets it sends. A sort of similar issue also affects Tweakeroo's fast block placement, where sometimes it misses some blocks here and there, and sometimes when you open your inventory there are items in the cursor, due to some failed inventory actions.

**Comment by mms0316** [comment]
From my investigations, this looks to be a problem more on the server side, and this seems ping related.

From previous experiences, having other mods that manage inventory, like Inventory Profiles Next's AutoRefill feature, the client's inventory tend to desync. I have a [video](https://www.youtube.com/watch?v=xLp70ZPblRY) showing that whenever a stack runs out, and another stack is moved to the hotbar (from both Inventory Profiles' AutoRefill feature and Litematica's pickBlock / easyPlace), it looks like an entire stack disappears, and eating food refreshes the inventory (at 1:13). Afterwards in the video I show that placing the blocks more slowly the client desync doesn't tend to happen.

Having `pickBlockShulkers` set to true and `easyPlaceUseKey` to NONE with `Allow empty keybind` to true, and having some materials inside shulker boxes, sometimes a shulker box is placed on the schematic block instead of only having the shulker box on hand. Since I didn't leave the default right-click hotkey for `easyPlaceUseKey`, it didn't seem like a client-side conflict.

At first, in Litematica, I tried validating that the stacks from the schematic and what's in the hand matched with this:
```
                // Abort if a wrong item is in the player's hand
                if (hand == null || stack.getItem() != mc.player.getStackInHand(hand).getItem())
                {
                    return ActionResult.FAIL;
                }
```
But that had no effect at all.

Then, I tried moving the final code from `doEasyPlaceAction` that calls `mc.interactionManager.interactBlock` to a scheduled task some ticks later (creating a class extending TaskBase), but for some reason I didn't find out, entering a server started taking more time, and it even seemed like Minecraft stopped responding.

Finally, I did the approach on the Pull Request, based on how `easyPlaceIsPositionCached` disregards an easyPlace action if it happens below 2 seconds on a same block, and setting a value above my ping looked to work (however, if I run or have speed potions, Litematica then may simply skip a block, but I feel it's better erring on a missing block than placing a wrong block).

If you find out a better approach, that'd be great, I have no issues if this code is replaced later for something better, especially since I added a config that may need different values depending on the player's ping.

**Pull request merged**
