### PR TITLE
Add schematic description

### PR DESCRIPTION
**Pull request by funnyboy-roks**
Add gui features for viewing/editing the description field on schematics, effectively completing #237.

One can edit the description of a schematic by clicking "Edit Description" in the schematic manager (`\n` gets converted to a newline)

The description field only gets rendered if the description is not blank.

This pr also changes the rendering of the icon in order to make it fit nicely with the description.

image

### CODE REVIEW

**Comment by vacla** [comment]
@funnyboy-roks it is better to look to the 1.12 rewrite branch as that one is up to date and this branch (pre-rewrite) won't add any features anymore

**Comment by funnyboy-roks** [comment]
Yeah, I saw that, though as I understand it, there is no port of the 1.12 rewrite to the later versions yet, and I wanted to use this feature.  If it gets merged, great, otherwise, I don't mind.

**Comment by maruohon** [comment]
At this point I'm not adding any new features to the 1.13+ versions of the mods anymore. I'm entirely focusing on the 1.12.2 development, so that I can at some point actually get it ready to be ported to other MC versions.

As for the description feature, I implemented showing the description text to the 1.12.2 code base at the end of last December.
Looks like I even added a button and a text field to edit the description to the Schematic Manager, although in the end it's meant to have a multi-line text area/text editor widget to edit the text, and I haven't implemented that to malilib yet.

**Comment by funnyboy-roks** [comment]
Ah, wonderful.  I'll close this PR then.  Thank you for your work on these awesome mods! :D

**Pull request closed without merging**
